# podajemy link do repo w którym znajduje siê plik konfiguracyjny 'configuration'
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Agata95/configuration.git
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka/
